# Generated by Django 5.1 on 2024-09-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=8, unique=True, verbose_name='ชื่อเขื่อน')),
                ('site_name', models.CharField(max_length=100, verbose_name='คำอธิบาย')),
                ('organization', models.CharField(max_length=8, verbose_name='องค์กร')),
            ],
        ),
    ]
