# Generated by Django 5.1 on 2024-09-20 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maximo_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_code', models.CharField(max_length=8, unique=True, verbose_name='รหัสโรงไฟฟ้า')),
                ('plant_type_th', models.CharField(max_length=100, verbose_name='ประเภทโรงไฟฟ้า (TH)')),
                ('plant_type_eng', models.CharField(max_length=100, verbose_name='ประเภทโรงไฟฟ้า (ENG)')),
            ],
        ),
    ]
