# Generated by Django 5.1 on 2024-09-20 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maximo_app', '0002_planttype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planttype',
            options={'verbose_name': 'ประเภทโรงไฟฟ้า', 'verbose_name_plural': 'ประเภทโรงไฟฟ้า'},
        ),
    ]
