# Generated by Django 5.1 on 2024-09-20 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maximo_app', '0004_alter_planttype_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planttype',
            options={'verbose_name': 'Plant Type', 'verbose_name_plural': 'Plant Type'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'verbose_name': 'Site', 'verbose_name_plural': 'Site'},
        ),
    ]
