# Generated by Django 5.1 on 2024-09-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maximo_app', '0005_alter_planttype_options_alter_site_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_code', models.CharField(max_length=8, unique=True, verbose_name='Block/Unit')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='คำอธิบาย')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Unit',
            },
        ),
        migrations.AlterField(
            model_name='site',
            name='site_id',
            field=models.CharField(max_length=8, unique=True, verbose_name='SITEID'),
        ),
    ]
