# Generated by Django 5.1 on 2024-09-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maximo_app', '0007_worktype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acttype', models.CharField(max_length=8, unique=True, verbose_name='ACTTYPE')),
                ('description', models.CharField(max_length=100, verbose_name='คำอธิบาย')),
                ('code', models.CharField(max_length=8, verbose_name='Code')),
                ('remark', models.CharField(blank=True, max_length=100, null=True, verbose_name='หมายเหตุ')),
            ],
            options={
                'verbose_name': 'ACTTYPE',
                'verbose_name_plural': 'ACTTYPE',
            },
        ),
        migrations.AlterModelOptions(
            name='worktype',
            options={'verbose_name': 'Work Type', 'verbose_name_plural': 'Work Type'},
        ),
    ]
