# Generated by Django 5.1 on 2024-09-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maximo_app', '0008_acttype_alter_worktype_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='WBSCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wbs_code', models.CharField(max_length=8, unique=True, verbose_name='WBS Code')),
                ('description', models.CharField(max_length=100, verbose_name='คำอธิบาย')),
            ],
            options={
                'verbose_name': 'WBS',
                'verbose_name_plural': 'WBS',
            },
        ),
        migrations.AlterModelOptions(
            name='acttype',
            options={'verbose_name': 'Act Type', 'verbose_name_plural': 'Act Type'},
        ),
    ]
