# Generated by Django 5.1 on 2024-10-01 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maximo_app', '0011_site_plant_types_alter_acttype_acttype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=8, unique=True, verbose_name='site_id')),
                ('site_name', models.CharField(max_length=100, verbose_name='site_name')),
            ],
            options={
                'verbose_name': 'Child Site',
                'verbose_name_plural': 'Child Site',
            },
        ),
    ]
