# Generated by Django 5.1 on 2024-10-01 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maximo_app', '0012_childsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='childsite',
            name='parent_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_sites', to='maximo_app.site'),
        ),
    ]
