# Generated by Django 5.1 on 2024-10-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maximo_app', '0013_childsite_parent_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='planttype',
            name='act_types',
            field=models.ManyToManyField(related_name='plant_types', to='maximo_app.acttype'),
        ),
    ]
