# Generated by Django 5.1 on 2024-10-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maximo_app', '0014_planttype_act_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='planttype',
            name='work_types',
            field=models.ManyToManyField(related_name='plant_types', to='maximo_app.worktype'),
        ),
    ]
