# Generated by Django 5.1 on 2024-10-01 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maximo_app', '0015_planttype_work_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acttype',
            name='remark',
        ),
    ]
